Zooe/Zooe/Controllers/EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zooe.Team10;

namespace Zooe.Controllers
{
    public class EventsController : Controller
    {
        private readonly Team10Context _context;

        public EventsController(Team10Context context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index()
        {
            var team10Context = _context.Event.Include(a => a.Department);
            return View(await team10Context.ToListAsync());
        }

        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .Include(a => a.Department)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Events/Create
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName");
            return View();
        }

        // POST: Events/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,DepartmentId,Date,Location,ImageUrl,Description")] Event @event)
        {
            if (ModelState.IsValid)
            {
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName", @event.DepartmentId);
            return View(@event);
        }

        // GET: Events/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName", @event.DepartmentId);
            return View(@event);
        }

        // POST: Events/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,DepartmentId,Date,Location,ImageUrl,Description")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Event _event = _context.Event.Where(s => s.EventId == @event.EventId).First();
                    _event.DepartmentId = @event.DepartmentId;
                    _event.Date = @event.Date;
                    _event.Location = @event.Location;
                    _event.ImageUrl = @event.ImageUrl;
                    _event.Description = @event.Description;
                    _context.Update(_event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName", @event.DepartmentId);
            return View(@event);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .Include(a => a.Department)
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Event.FindAsync(id);
            _context.Event.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Event.Any(e => e.EventId == id);
        }
    }
}

Zooe/Zooe/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zooe.Team10;

namespace Zooe.Controllers
{
    public class ItemsController : Controller
    {
        private readonly Team10Context _context;

        public ItemsController(Team10Context context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            var team10Context = _context.Items.Include(i => i.Shop);
            return View(await team10Context.ToListAsync());
        }

        public async Task<IActionResult> Shop()
        {
            var team10Context = _context.Items.Include(i => i.Shop);
            return View(await team10Context.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items
                .Include(i => i.Shop)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["ShopId"] = new SelectList(_context.GiftShop, "ShopId", "Description");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,ShopId,Title,ImageUrl,Price,StockCount")] Items items)
        {
            if (ModelState.IsValid)
            {
                _context.Add(items);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShopId"] = new SelectList(_context.GiftShop, "ShopId", "Description", items.ShopId);
            return View(items);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items.FindAsync(id);
            if (items == null)
            {
                return NotFound();
            }
            ViewData["ShopId"] = new SelectList(_context.GiftShop, "ShopId", "Description", items.ShopId);
            return View(items);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,ShopId,Title,ImageUrl,Price,StockCount")] Items items)
        {
            if (id != items.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Items _items = _context.Items.Where(s => s.ItemId == items.ItemId).First();
                    _items.Title = items.Title;
                    _items.ImageUrl = items.ImageUrl;
                    _items.Price = items.Price;
                    _items.StockCount = items.StockCount;
                    _context.Update(_items);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemsExists(items.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShopId"] = new SelectList(_context.GiftShop, "ShopId", "Description", items.ShopId);
            return View(items);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items
                .Include(i => i.Shop)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var items = await _context.Items.FindAsync(id);
            _context.Items.Remove(items);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemsExists(int id)
        {
            return _context.Items.Any(e => e.ItemId == id);
        }
    }
}

Zooe/Zooe/Controllers/StaffsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zooe.Team10;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Zooe.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StaffsController : Controller
    {
        private readonly Team10Context _context;

        public StaffsController(Team10Context context)
        {
            _context = context;
        }

        // GET: Staffs
        public async Task<IActionResult> Index()
        {
            var team10Context = _context.Staff.Include(s => s.Department);
            return View(await team10Context.ToListAsync());
        }

        // GET: Staffs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .Include(s => s.Department)
                .FirstOrDefaultAsync(m => m.StaffId == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // GET: Staffs/Create
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName");
            return View();
        }

        // POST: Staffs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StaffId,DepartmentId,FirstName,LastName,JobTitle,EmailAddress,HomeAddress,Salary,StartDate")] Staff staff)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staff);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName", staff.DepartmentId);
            return View(staff);
        }

        // GET: Staffs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff.FindAsync(id);
            if (staff == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName", staff.DepartmentId);
            return View(staff);
        }

        // POST: Staffs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StaffId,DepartmentId,FirstName,LastName,JobTitle,EmailAddress,HomeAddress,Salary,StartDate")] Staff staff)
        {
            if (id != staff.StaffId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Staff _staff = _context.Staff.Where(s => s.StaffId == staff.StaffId).First();
                    _staff.DepartmentId = staff.DepartmentId;
                    _staff.FirstName = staff.FirstName;
                    _staff.LastName = staff.LastName;
                    _staff.JobTitle = staff.JobTitle;
                    _staff.EmailAddress = staff.EmailAddress;
                    _staff.HomeAddress = staff.HomeAddress;
                    _staff.Salary = staff.Salary;
                    _context.Update(_staff);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffExists(staff.StaffId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName", staff.DepartmentId);
            return View(staff);
        }

        // GET: Staffs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var staff = await _context.Staff
                .Include(s => s.Department)
                .FirstOrDefaultAsync(m => m.StaffId == id);
            if (staff == null)
            {
                return NotFound();
            }

            return View(staff);
        }

        // POST: Staffs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var staff = await _context.Staff.FindAsync(id);
            _context.Staff.Remove(staff);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffExists(int id)
        {
            return _context.Staff.Any(e => e.StaffId == id);
        }
    }
}

Zooe/Zooe/Views/Home/Admin.cshtml
@{
    ViewData["Title"] = "Sourvenirs";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #header {
        background-color: black;
    }
</style>

<body id="exhibit-body">

    <main id="main">
        <section id="about">
            <div class="container">



                <div class="row about-cols">

                    <main>


                        <!-- Category Area Start-->
                        <section class="category-area section-padding30">







                            <!-- Section Tittle -->
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="section-tittle text-center mb-85">
                                        <h2>Admin</h2>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","Animals") ">
                                            <div class="category-img figure">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" class="figure-img img-fluid rounded" alt=" ">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Animals</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","Customers")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Customers</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","Departments")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" style="height:376px" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Departments</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","Events")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" style="height:376px" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Events</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","Exhibits")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" style="height:376px" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Exhibits</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","GiftShops")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" style="height:376px" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">GiftShops</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","ItemPurchases")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" style="height:376px" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Item Purchases</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","Items")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" style="height:376px" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Items</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","PrivateEvents")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" style="height:376px" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Private Events</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","Staffs")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" style="height:376px" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Staffs</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-4 col-lg-6">
                                    <div class="single-category mb-30">
                                        <a style="text-decoration:none;color:black" href="@Url.Action("Index","TicketPurchases")">
                                            <div class="category-img text-center">
                                                <img src="@Url.Content("https://via.placeholder.com/300/09f/fff.png")" style="height:376px" alt="">
                                                <div class="caption">
                                                    <h3 style="text-align:center">Ticket Purchases</h3>
                                                </div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            </div>


                        </section>

                    </main>
                </div>
            </div>
        </section>
    </main>
</body>

Zooe/Zooe/Views/Home/TicketCheckout.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@