Zooe/Zooe/Controllers/GiftShopsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zooe.Team10;

namespace Zooe.Controllers
{
    public class GiftShopsController : Controller
    {
        private readonly Team10Context _context;

        public GiftShopsController(Team10Context context)
        {
            _context = context;
        }

        // GET: GiftShops
        public async Task<IActionResult> Index()
        {
            var team10Context = _context.GiftShop.Include(g => g.Department);
            return View(await team10Context.ToListAsync());
        }
        public async Task<IActionResult> Shop()
        {
            var team10Context = _context.GiftShop.Include(g => g.Department);
            return View(await team10Context.ToListAsync());
        }

        // GET: GiftShops/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giftShop = await _context.GiftShop
                .Include(g => g.Department)
                .FirstOrDefaultAsync(m => m.ShopId == id);
            if (giftShop == null)
            {
                return NotFound();
            }

            return View(giftShop);
        }

        // GET: GiftShops/Create
        public IActionResult Create()
        {
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName");
            return View();
        }

        // POST: GiftShops/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ShopId,DepartmentId,ShopName,Description,ImageUrl,Location")] GiftShop giftShop)
        {
            if (ModelState.IsValid)
            {
                _context.Add(giftShop);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName", giftShop.DepartmentId);
            return View(giftShop);
        }

        // GET: GiftShops/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giftShop = await _context.GiftShop.FindAsync(id);
            if (giftShop == null)
            {
                return NotFound();
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName", giftShop.DepartmentId);
            return View(giftShop);
        }

        // POST: GiftShops/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ShopId,DepartmentId,ShopName,Description,ImageUrl,Location")] GiftShop giftShop)
        {
            if (id != giftShop.ShopId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    GiftShop _giftShop = _context.GiftShop.Where(s => s.ShopId == giftShop.ShopId).First();
                    _giftShop.DepartmentId = giftShop.DepartmentId;
                    _giftShop.ShopName = giftShop.ShopName;
                    _giftShop.Description = giftShop.Description;
                    _giftShop.ImageUrl = giftShop.ImageUrl;
                    _giftShop.Location = giftShop.Location;
                    _context.Update(_giftShop);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GiftShopExists(giftShop.ShopId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["DepartmentId"] = new SelectList(_context.Department, "DepartmentId", "DepartmentName", giftShop.DepartmentId);
            return View(giftShop);
        }

        // GET: GiftShops/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var giftShop = await _context.GiftShop
                .Include(g => g.Department)
                .FirstOrDefaultAsync(m => m.ShopId == id);
            if (giftShop == null)
            {
                return NotFound();
            }

            return View(giftShop);
        }

        // POST: GiftShops/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var giftShop = await _context.GiftShop.FindAsync(id);
            _context.GiftShop.Remove(giftShop);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool GiftShopExists(int id)
        {
            return _context.GiftShop.Any(e => e.ShopId == id);
        }
    }
}

Zooe/Zooe/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Zooe.Team10;

namespace Zooe.Controllers
{
    public class ItemsController : Controller
    {
        private readonly Team10Context _context;

        public ItemsController(Team10Context context)
        {
            _context = context;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            var team10Context = _context.Items.Include(i => i.Shop);
            return View(await team10Context.ToListAsync());
        }

        public async Task<IActionResult> Shop()
        {
            var team10Context = _context.Items.Include(i => i.Shop);
            return View(await team10Context.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items
                .Include(i => i.Shop)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["ShopId"] = new SelectList(_context.GiftShop, "ShopId", "Description");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,ShopId,Title,ImageUrl,Price,StockCount")] Items items)
        {
            if (ModelState.IsValid)
            {
                _context.Add(items);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShopId"] = new SelectList(_context.GiftShop, "ShopId", "Description", items.ShopId);
            return View(items);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items.FindAsync(id);
            if (items == null)
            {
                return NotFound();
            }
            ViewData["ShopId"] = new SelectList(_context.GiftShop, "ShopId", "Description", items.ShopId);
            return View(items);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,ShopId,Title,ImageUrl,Price,StockCount")] Items items)
        {
            if (id != items.ItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Items _items = _context.Items.Where(s => s.ItemId == items.ItemId).First();
                    _items.Title = items.Title;
                    _items.ImageUrl = items.ImageUrl;
                    _items.Price = items.Price;
                    _items.StockCount = items.StockCount;
                    _context.Update(_items);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemsExists(items.ItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShopId"] = new SelectList(_context.GiftShop, "ShopId", "Description", items.ShopId);
            return View(items);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var items = await _context.Items
                .Include(i => i.Shop)
                .FirstOrDefaultAsync(m => m.ItemId == id);
            if (items == null)
            {
                return NotFound();
            }

            return View(items);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var items = await _context.Items.FindAsync(id);
            _context.Items.Remove(items);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemsExists(int id)
        {
            return _context.Items.Any(e => e.ItemId == id);
        }
    }
}

Zooe/Zooe/Views/Items/Create.cshtml
@model Zooe.Team10.Items

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Items</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ShopId" class="control-label"></label>
                <select asp-for="ShopId" class ="form-control" asp-items="ViewBag.ShopId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockCount" class="control-label"></label>
                <input asp-for="StockCount" class="form-control" />
                <span asp-validation-for="StockCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

Zooe/Zooe/Views/Items/Delete.cshtml
@model Zooe.Team10.Items

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Items</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shop.ShopName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ItemId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Zooe/Zooe/Views/Items/Details.cshtml
@model Zooe.Team10.Items

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>Items</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StockCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StockCount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Shop)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Shop.ShopName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ItemId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Zooe/Zooe/Views/Items/Edit.cshtml
@model Zooe.Team10.Items

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Items</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ItemId" />
            <div class="form-group">
                <label asp-for="ShopId" class="control-label"></label>
                <select asp-for="ShopId" class="form-control" asp-items="ViewBag.ShopId"></select>
                <span asp-validation-for="ShopId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockCount" class="control-label"></label>
                <input asp-for="StockCount" class="form-control" />
                <span asp-validation-for="StockCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

</body>
</html>

Zooe/Zooe/Views/Items/Shop.cshtml
@model IEnumerable<Zooe.Team10.Items>

@{
    ViewData["Title"] = "Shop";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<style>
    img {
        width: 340px;
        height: 255px;
    }

    h4 {
        text-align: center;
    }

    .price {
        text-align: center;
    }

    .zoom {
        padding: 50px;
        transition: transform .2s; /* Animation */
        width: 400px;
        height: 300px;
        margin: 0 auto;
    }
    .show{
        display:block !important;
    }
    .sort{
        display: none;
    }
        .zoom:hover {
            transform: scale(1.5); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
        }
</style>


<body>
    <section id="intro">
        <div class="intro-container">
            <div id="introCarousel" class="carousel  slide carousel-fade" data-ride="carousel">

                <ol class="carousel-indicators"></ol>

                <div class="carousel-inner" role="listbox">

                    <div class="carousel-item active">
                        <div class="carousel-background"><img src="~/Content/img/cafe.jpg" alt=""></div>
                        <div class="carousel-container">
                            <div class="carousel-caption">
                                <h2>Zoo Shop</h2>
                                <p>Take a look at the various Zoo products we have for sale!</p>
                                <a class="btn-get-started scrollto" href="@Url.Action("Index", "Home")">Explore</a>
                            </div>
                        </div>
                    </div>

                    <div class="carousel-item">
                        <div class="carousel-background"><img src="~/Content/img/food.jpg" alt=""></div>
                        <div class="carousel-container">
                            <div class="carousel-caption">
                                <h2>Recreation Plushies</h2>
                                <p>Get a little Riot to take home!</p>
                                <a class="btn-get-started scrollto" href="@Url.Action("Index", "Home")">Explore</a>
                            </div>
                        </div>
                    </div>

                </div>

                <a class="carousel-control-prev" href="#introCarousel" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon ion-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>

                <a class="carousel-control-next" href="#introCarousel" role="button" data-slide="next">
                    <span class="carousel-control-next-icon ion-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>

            </div>
        </div>
    </section><!-- End Intro Section -->

    <main>


        <!-- Category Area Start-->
        <section class="category-area section-padding30">
            <div class="container-fluid">

                <nav class="navbar navbar-expand-lg navbar-light">


                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        
                        <form class="form-inline my-2 my-lg-0" method="POST">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i></button>
                        </form>

                    </div>
                </nav>







                <!-- Section Tittle -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-tittle text-center mb-85">
                            <h2>Shop by Category</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xl-4 col-lg-6">
                        <div class="single-category mb-30">
                            <a style="text-decoration:none;color:black" href="@Url.Action("Shop","Items") ">
                                <div class="category-img figure">
                                    <img src="@Url.Content("~/Content/assets_store/img/categori/Food.jpg")" class="figure-img img-fluid rounded" alt=" ">
                                    <div class="caption">
                                        <h3 style="text-align:center">Food</h3>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-6">
                        <div class="single-category mb-30">
                            <a style="text-decoration:none;color:black" href="@Url.Action("Sourvenirs","Home")">
                                <div class="category-img text-center">
                                    <img src="@Url.Content("~/Content/assets_store/img/categori/toy.jpg")" style="height:376.41px" alt="">
                                    <div class="caption">
                                        <h3 style="text-align:center">Souvenirs</h3>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-xl-4 col-lg-6">
                        <div class="single-category mb-30">
                            <a style="text-decoration:none;color:black" href="@Url.Action("Shop","GiftShops")">
                                <div class="category-img text-center">
                                    <img src="@Url.Content("~/Content/cafe.jpg")" style="height:376px" alt="">
                                    <div class="caption">
                                        <h3 style="text-align:center">Cafe</h3>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Category Area End-->
        <!-- Latest Products Start -->
        <section class="latest-product-area padding-bottom">
            <div class="container">
                <div class="row product-btn d-flex justify-content-end align-items-end">
                    <!-- Section Tittle -->
                    <div class="col-xl-4 col-lg-5 col-md-5" id="scroll">
                        <div class="section-tittle mb-30">
                            <h2>Menu</h2>
                        </div>
                    </div>
                    
                    <div class="col-xl-8 col-lg-7 col-md-7">
                        <div class="properties__button f-right">
                            <!--Nav Button  -->
                            <div id="myBtnContainer">
                                <button class="btn active" onclick="filterSelection('all')"> Show all</button>
                                <button class="btn" onclick="filterSelection('Salad')"> Salad</button>
                                <button class="btn" onclick="filterSelection('Wrap')"> Wrap</button>
                                <button class="btn" onclick="filterSelection('Sandwich')"> Sandwich</button>
                                <button class="btn" onclick="filterSelection('Water')"> Water</button>
                            </div>
                          
                            <!--End Nav Button  -->
                        </div>
                    </div>
                </div>
                <!-- Nav Card -->
                <div class="tab-content" id="nav-tabContent">
                    <!-- card one -->
                    <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                        <div class="row">
                            @foreach (var item in Model)
                            {
                                <div class="col-xl-4 col-lg-4 col-md-6 sort @Html.DisplayFor(modelItem=>item.Title)">
                                    <div class="single-product mb-60">
                                        <div class="product-img">
                                            <img src="@Html.DisplayFor(modelItem=>item.ImageUrl)" 
                                                 alt="@Html.DisplayFor(modelItem=>item.Title)" 
                                                 class="zoom ">

                                        </div>
                                        <div class="product-caption">

                                            <h4>@Html.DisplayFor(modelItem => item.Title)</h4>

                                            <div class="price">
                                                <ul>
                                                    <li>@Html.DisplayFor(modelItem => item.Price)</li>

                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                            }
                        </div>
                    </div>
                </div>

                <script>
                    function filterSelection(c) {
                        var x, i;
                        x = document.getElementsByClassName("sort");
                        if (c == "all") c = "";
                        
                        for (i = 0; i < x.length; i++) {
                            x[i].classList.remove("class", "show");
                            if (x[i].className.indexOf(c) > -1) x[i].classList.add("class", "show");
                        }
                    }
                    filterSelection('all');
                    //function filterSelection(c) {
                        
                    //}

                    //function w3AddClass(element, name) {
                    //    var i, arr1, arr2;
                    //    arr1 = element.className.split(" ");
                    //    arr2 = name.split(" ");
                    //    for (i = 0; i < arr2.length; i++) {
                    //        if (arr1.indexOf(arr2[i]) == -1) {
                    //            element.className += " " + arr2[i];
                    //        }
                    //    }
                    //}

                    //function w3RemoveClass(element, name) {
                    //    var i, arr1, arr2;
                    //    arr1 = element.className.split(" ");
                    //    arr2 = name.split(" ");
                    //    for (i = 0; i < arr2.length; i++) {
                    //        while (arr1.indexOf(arr2[i]) > -1) {
                    //            arr1.splice(arr1.indexOf(arr2[i]), 1);
                    //        }
                    //    }
                    //    element.className = arr1.join(" ");
                    //}
                    //var btnContainer = document.getElementById("myBtnContainer");
                    //var btns = btnContainer.getElementsByClassName("btn");
                    //for (var i = 0; i < btns.length; i++) {
                    //    btns[i].addEventListener("click", function () {
                    //        var current = document.getElementsByClassName("active");
                    //        current[0].className = current[0].className.replace(" active", "");
                    //        this.className += " active";
                    //    });
                    //filterSelection("all") // Execute the function and show all columns
                </script>
            </div>
        </section>
        <!-- Latest Products End -->
        <!-- Best Product Start -->


    </main>
</body>